trigger:
- master
- feature/*

pool: bootcampApp-pool

variables:
- group: repo
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '783185f1-f3b8-40c5-8d47-f8df1bef5828'
  imageRepository: 'kostyabootcampimage'
  containerRegistry: 'kostyaf91bootcampreg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: $(Build.BuildId)

stages:
### CI ###
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    steps:
    - task: Docker@2
      displayName: Build an image 
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        dockerfile: $(dockerfilePath)
        tags: $(tag)
    - task: Docker@2
      displayName: Push an image to ACR
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)
        
### Deploying to staging ###
- stage: Deploy_to_staging
  variables:
  - group: staging
  - group: repo
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: staging
    displayName: 'Deploy bootcamp-app' 
    environment:
      name: staging
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              rm -rf weight_tracker_ansible
              git clone https://github.com/kostyaf91/weight_tracker_ansible
          - task: Ansible@0
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'weight_tracker_ansible/playbook.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'weight_tracker_ansible/inventories/staging/inventory'
              args: '-e "lb-ip=$(lb-ip) okta-id=$(okta-id) okta-secret=$(okta-secret) postgres-pass=$(postgres-pass) vm-pass=$(vm-pass) pgHost=$(pgHost) acrLogin=$(acrLogin) acrPass=$(acrPass) registry=$(registry) tag=$(tag)"'
              failOnStdErr: false

### Deploying to production ###
- stage: Deploy_to_prod
  variables:
  - group: prod
  - group: repo
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: prod
    displayName: 'Deploy bootcamp-app' 
    environment:
      name: prod
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              rm -rf weight_tracker_ansible
              git clone https://github.com/kostyaf91/weight_tracker_ansible
          - task: Ansible@0
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'weight_tracker_ansible/playbook.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'weight_tracker_ansible/inventories/prod/inventory'
              args: '-e "lb-ip=$(lb-ip) okta-id=$(okta-id) okta-secret=$(okta-secret) postgres-pass=$(postgres-pass) vm-pass=$(vm-pass) pgHost=$(pgHost) acrLogin=$(acrLogin) acrPass=$(acrPass) registry=$(registry) tag=$(tag)"'
              failOnStdErr: false