trigger:
  branches:
    include:
    - master
    - feature/*
pool:
  name: bootcampApp-pool
variables:
- group: global
stages:
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'ACR connection'
        repository: 'bootcampapp'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push an image to ACR
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        containerRegistry: 'ACR connection'
        repository: 'bootcampapp'
        command: 'push'
        tags: '$(tag)'
- stage: Deploy_to_staging
  variables:
  - group: staging
  - group: repo
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: staging
    displayName: 'Deploy bootcamp-app'
    environment:
      name: staging
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                rm -rf weight_tracker_ansible
                git clone https://github.com/kostyaf91/weight_tracker_ansible
          - task: Ansible@0
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'weight_tracker_ansible/playbook.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'weight_tracker_ansible/inventories/staging/inventory'
              args: '-e "lb_ip=$(lb_ip) okta_id=$(okta_id) okta_secret=$(okta_secret) postgres_pass=$(postgres_pass) vm_pass=$(vm_pass) pgHost=$(pgHost) acrLogin=$(acrLogin) acrPass=$(acrPass) registry=$(registry) tag=$(tag) "'
              failOnStdErr: false
- stage: Deploy_to_prod
  variables:
  - group: prod
  - group: repo
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: prod
    displayName: 'Deploy bootcamp-app'
    environment:
      name: prod
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                rm -rf weight_tracker_ansible
                git clone https://github.com/kostyaf91/weight_tracker_ansible
          - task: Ansible@0
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'weight_tracker_ansible/playbook.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'weight_tracker_ansible/inventories/prod/inventory'
              args: '-e "lb_ip=$(lb_ip) okta_id=$(okta_id) okta_secret=$(okta_secret) postgres_pass=$(postgres_pass) vm_pass=$(vm_pass) pgHost=$(pgHost) acrLogin=$(acrLogin) acrPass=$(acrPass) registry=$(registry) tag=$(tag)"'
              failOnStdErr: false

