- hosts: servers
  become: yes
  gather_facts: no
  ignore_unreachable: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: pip3 and docker instalation
      apt:
        name:
          - python3-pip
          - docker.io
        state: present

    - name: Install docker using pip
      pip:
        name: docker-py

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: kostyaf91bootcampreg.azurecr.io
        username: "{{ acrLogin }}"
        password: "{{ acrPass }}"
        reauthorize: yes
    - name: pull an image
      docker_image:
        name: kostyaf91bootcampreg.azurecr.io/kostyabootcampimage:latest
        source: pull

    - name: Stop running container if present
      shell: docker stop $(docker ps)
      ignore_errors: yes

    - name: Start weight app container
      shell: docker run -d --restart=always -p 8080:8080 kostyaf91bootcampreg.azurecr.io/kostyabootcampimage:latest
